#!/bin/bash

SYSTEM=$1
IP=$2
SERVER_IP=$3

if [ $SYSTEM = "altlinux" ]
then
	ssh root@$IP "echo ${SERVER_IP}:8080 >> /etc/hosts"
elif [ $SYSTEM = "astra" ]
then
	ssh root@$IP "echo ${SERVER_IP}:8080 >> /etc/hosts"
elif [ $SYSTEM = '"redos"' ]
then
	ssh root@$IP "echo ${SERVER_IP}:8080 >> /etc/hosts"
else
	exit 1
fi
